### ISSUE TITLE
Wireguard Go for MIPS

### ISSUE THREAD

**Issue by hcr2020** [seud0nym/openwrt-wireguard-go#1]
Hello
I hava a TG789vac v2 with chaos calmer 15.05 and I installed openvpn on it using a compiled tun.ko 
https://alastair.d-silva.org/technicolor-tg789vac-v2-root-access
(https://web.archive.org/web/20210304005924/https://alastair.d-silva.org/technicolor-tg789vac-v2-root-access)
I run latest  adguard home and dnscrypt2 which are dependent on Go . Is it possible if you could compile a MIPS release for my router ?
Thanks in advance

**Comment by seud0nym** [comment]
I have added `openwrt-wireguard-go_mips.tgz` to the latest release page.

Let me know how you go.

**Comment by hcr2020** [comment]
Thank you very much, I will try ASAP , when I return home (Monday); Thanks for your quick response , will report back

**Comment by hcr2020** [comment]
Sorry for the late feedback.
I tried multiple times and it crashed my router.
But here is my config based upon a free account on vpnjantit.com:

I placed  these config in 
`/etc/wireguard/wg0.conf`

>[Interface]
 Address = 192.168.6.229/32
DNS = 8.8.8.8
PrivateKey = ***********************************************=
[Peer]
Publickey=********************************************=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = fr2.vpnjantit.com:51820
PersistentKeepalive = 25 




But it didn't see it correctly 
`# wg-go setconf wg0 /etc/wireguard/wg0.conf'

> 2022/05/21 19:12:55 Parse error: invalid key Address for Interface section, (line 1)

I couldn't make it run.
I tried

`ip link add dev wg0 type wireguard'

> RTNETLINK answers: Operation not supported

here is my etc/config/network

> `config interface 'wg0'
	option proto 'wireguard'
	option private_key '*********************************='
	option listen_port '51820'
	list addresses '192.168.6.229/32'
	option ipv6 '0'
	option enabled '0'### do not enable or it will crash upon boot

> config wireguard_wg0
	list dns '8.8.8.8'
	option delegate '0'
	option route_allowed_ips '1'
	option persistent_keepalive '25'
	list allowed_ips '0.0.0.0/0'
	#list allowed_ips '::/0'
	option public_key '***********************************='
	option endpoint_host 'fr2.vpnjantit.com'`

` wg-go showconf /etc/wireguard/wg0.conf'
> 2022/05/21 19:42:50 file does not exist

I appreciate any help, Thank you

**Comment by seud0nym** [comment]
> wg-go setconf wg0 /etc/wireguard/wg0.conf
> ip link add dev wg0 type wireguard

You don't need to do these things. This is not the way that WireGuard is configured on OpenWrt. These commands happen automatically after you have configured /etc/config/network correctly.

The [Usage ](https://github.com/seud0nym/openwrt-wireguard-go#usage) instructions clearly state that you need to use the official OpenWRT guides at https://openwrt.org/docs/guide-user/services/vpn/wireguard/start to configure WireGuard as a [server](https://openwrt.org/docs/guide-user/services/vpn/wireguard/server) and/or a [client](https://openwrt.org/docs/guide-user/services/vpn/wireguard/client).

> I tried multiple times and it crashed my router.

What error messages are logged?

**Comment by hcr2020** [comment]
Hello again
If it hangs, I am forced to powercycle the modem , so I can't have logs.

**Comment by seud0nym** [comment]
All syslog messages are stored in `/root/log/messages.log` (older messages are stored in `/root/log/messages.log.0`). These files survive a reboot.
