### ISSUE TITLE
Failed to determine executable: readlink /proc/self/exe:   on MIPS release

### ISSUE THREAD

**Issue by roma21515** [seud0nym/openwrt-wireguard-go#2]
Hello i run wireguard-go on my router and have this error. In router no /proc/self/exe.   PID programs detect in var/run/

fix it please

root@OpenWrt:~# wireguard-go wg0
ERROR: (wg0) 2024/03/29 08:44:24 Failed to determine executable: readlink /proc/self/exe: no such file or directory

**Comment by seud0nym** [comment]
I do not have MIPS device on which I can test this. I only created the MIPS release as the result of an issue request (https://github.com/seud0nym/openwrt-wireguard-go/issues/1).

Also, wireguard-go included in the package is a built from the latest release tag (at the moment 0.0.20230223) of the code maintained at https://git.zx2c4.com/wireguard-go. I make 2 modifications to the code to reduce the memory footprint and remove the code that prevents it from running on Linux. Apart from that, I am just a _user_ of the codebase, not a maintainer.

I would recommend that you build wireguard-go from source yourself using the latest code, and see if that fixes your problem. If it doesn't, you will need to open an issue with the maintainer of that repository.

**Comment by roma21515** [comment]
I did just that, the problem is with the UPX packer, it starts without compression. But without compression I don’t have enough space (. True, I still don’t understand how to set up openwrt. I’ve set everything up, but as soon as I open the interface, the Internet immediately disappears(

**Comment by roma21515** [comment]
I figured it out and set it up, but the speed is low..

**Comment by seud0nym** [comment]
I am glad you got it sorted out. 

Speed can be variable.
